// ignore_for_file: non_constant_identifier_names

class PlaceInfo {
  final String location,
      image,
      image1,
      image2,
      image3,
      image4,
      image5,
      hotel1,
      hotel2,
      // hotel3,
      // hotel4,
      hname1,
      hname2,
      // hname3,
      // hname4,
      rest1,
      rest2,
      // rest3,
      // rest4,
      rname1,
      rname2,
      // rname3,
      // rname4,
      name,
      rating,
      description;

  PlaceInfo({
    required this.location,
    required this.description,
    required String this.rating,
    required this.name,
    required this.image,
    required this.image1,
    required this.image2,
    required this.image3,
    required this.image4,
    required this.image5,
    required this.hotel1,
    required this.hotel2,
    // required this.hotel3,
    // required this.hotel4,
    required this.hname1,
    required this.hname2,
    // required this.hname3,
    // required this.hname4,
    required this.rest1,
    required this.rest2,
    // required this.rest3,
    // required this.rest4,
    required this.rname1,
    required this.rname2,
    // required this.rname3,
    // required this.rname4,
  });
}

List places = [
  PlaceInfo(
    location: '',
    image: 'assets/images/Vat.jpg',
    name: 'ວັດຊຽງທອງ',
    description: 'Thatluang is a patriarchy of the city of Laos',
    rating: '5.0',
    image1: 'assets/images/VatXTH1.jpg',
    image2: 'assets/images/VatXTH2.jpg',
    image3: 'assets/images/VatXTH3.jpg',
    image4: 'assets/images/VatXTH4.jpg',
    image5: 'assets/images/VatXTH5.jpg',
    hotel1: 'assets/images/Victoria.jpg',
    hotel2: 'assets/images/Burasari.jpg',
    hname1: 'Victoria XiengThong',
    hname2: 'Burasari Heritage',
    rest1: 'assets/images/restaurant.jpg',
    rest2: 'assets/images/noodlesoup.jpg',
    rname1: 'Viewpoint restaurant',
    rname2: 'Noodel Soup',
  ),
  PlaceInfo(
    location: '',
    image: 'assets/images/TatKSI.jpg',
    name: 'ນໍ້າຕົກຕາດກວາງຊີ',
    description: 'Thatluang is a patriarchy of the city of Laos',
    rating: '5.0',
    image1: 'assets/images/TatKSI1.jpg',
    image2: 'assets/images/TatKSI2.jpg',
    image3: 'assets/images/TatKSI3.jpg',
    image4: 'assets/images/TatKSI4.jpg',
    image5: 'assets/images/TatKSI5.jpg',
    hotel1: 'assets/images/HKSI1.jpg',
    hotel2: 'assets/images/HKSI2.jpg',
    hname1: 'Vanvisa The Falls',
    hname2: 'Pullman LPB',
    rest1: 'assets/images/RKSI1.jpg',
    rest2: 'assets/images/RKSI2.jpg',
    rname1: 'Carpe Diem',
    rname2: 'Nakhoun Cafe',
  ),
  PlaceInfo(
    location: '',
    image: 'assets/images/TATVT.jpg',
    name: 'ພຣະທາດຫຼວງວຽງຈັນ',
    description: 'Thatluang is a patriarchy of the city of Laos',
    rating: '5.0',
    image1: 'assets/images/TATVT1.jpg',
    image2: 'assets/images/TATVT2.jpg',
    image3: 'assets/images/TATVT3.jpg',
    image4: 'assets/images/TATVT4.jpg',
    image5: 'assets/images/TATVT5.jpg',
    hotel1: 'assets/images/HTATVT1.jpg',
    hotel2: 'assets/images/HTATVT2.jpg',
    hname1: 'Phasouk Vien Chantra',
    hname2: 'Grand Hotel',
    rest1: 'assets/images/RTATVT1.jpg',
    rest2: 'assets/images/RTATVT2.jpg',
    rname1: 'Metisse Restuarant',
    rname2: 'Doi Ka Noi Restuarant',
  ),
  PlaceInfo(
    location: '',
    image: 'assets/images/PTXVT.jpg',
    name: 'ປະຕູໄຊ',
    description: 'Thatluang is a patriarchy of the city of Laos',
    rating: '5.0',
    image1: 'assets/images/PTXVT1.jpg',
    image2: 'assets/images/PTXVT2.jpg',
    image3: 'assets/images/PTXVT3.jpg',
    image4: 'assets/images/PTXVT4.jpg',
    image5: 'assets/images/PTXVT5.jpg',
    hotel1: 'assets/images/HPTXVT1.jpg',
    hotel2: 'assets/images/HPTXVT2.jpg',
    hname1: 'Vientiane Plaza',
    hname2: 'Urbanite Hotel',
    rest1: 'assets/images/RPXTVT1.jpg',
    rest2: 'assets/images/RPXTVT2.jpg',
    rname1: 'Urdu Cafe',
    rname2: 'Tamnan Lao',
  ),
  PlaceInfo(
    location: '',
    image: 'assets/images/XKVT.jpg',
    name: 'ສວນວັດທະນາທຳຊຽງຄວນ',
    description: 'Thatluang is a patriarchy of the city of Laos',
    rating: '5.0',
    image1: 'assets/images/XKVT1.jpg',
    image2: 'assets/images/XKVT2.jpg',
    image3: 'assets/images/XKVT3.jpg',
    image4: 'assets/images/XKVT4.jpg',
    image5: 'assets/images/XKVT5.jpg',
    hotel1: 'assets/images/HXKVT1.jpg',
    hotel2: 'assets/images/HXKVT2.jpg',
    hname1: 'ST Vegas Resort',
    hname2: 'The Qube Hotel & Suite',
    rest1: 'assets/images/HXKVT1.jpg',
    rest2: 'assets/images/HXKVT1.jpg',
    rname1: 'Null',
    rname2: 'Null',
  ),
];
